### ISSUE TITLE
How do I use `macNotifications.py` with `db-wal`?

### ISSUE THREAD

**Issue by NightMachinery** [ydkhatri/MacForensics#2]
The notification I want to recover is present in `db-wal`, but it is not yet in `db`. It was also deleted via the remote source, so I am not sure it would be present if I merge the write-ahead log into `db`. Which I also don't know how to do, anyway.

**Comment by ydkhatri** [comment]
If you put both the db and the db-wal files in the same folder, then open the db file within any sqlite viewer (such as DB browser for sqlite), then it should automatically pull in the contents of the db-wal file. You should be able to manually verify then whether the content you seek is there. If not, it may be because the content was deleted. 

If it is then showing up , the script should parse it out for you too.

The script currently does not do any special processing to attempt to get deleted data, so it would not be read/parsed if it's deleted data.

**Comment by NightMachinery** [comment]
Thanks.
